# docker-compose.yml
version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    # depends_on:
    #   - website-1
    #   - website-2
    #   - website-3

  website-1:
    build: ./website-1
    deploy:
      replicas: 2


  website-2:
    build: ./website-2
    deploy:
      replicas: 2

  website-3:
    build: ./website-3
    deploy:
      replicas: 2
